routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdsController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    // Logout
    Route::get('/logout', [HomeController::class,'logout'])->name('logout');
    // Profile
    Route::get('/profile', [ProfileController::class,'index'])->name('profile.index');
    Route::post('/profile', [ProfileController::class,'store'])->name('profile.store');
    // Home
    Route::get('/', [HomeController::class,'index'])->name('home');

    Route::resource('users', UserController::class);
    Route::resource('ads', AdsController::class);
});

resources/views/layouts/inc/breadcrumb.blade.php
@if (isset($breadcrumb))
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                <h4 class="mb-sm-0 font-size-18">{{ $breadcrumb['title'] }}</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item">
                            <a href="{{ route('home') }}">
                                @lang('Dashboard')
                            </a>
                        </li>
                        <?php 
                            $last  = count($breadcrumb['items']);
                            $index = 1;
                        ?>
                        @foreach ($breadcrumb['items'] as $item)
                            @if ($index != $last)
                                <li class="breadcrumb-item">
                                    <a href="{{ $item['url'] }}">
                                        {{ $item['title'] }}
                                    </a>
                                </li>   
                            @else
                                <li class="breadcrumb-item active">
                                    {{ $item['title'] }}
                                </li>
                            @endif
                            <?php $index++; ?>
                        @endforeach
                    </ol>
                </div>

            </div>
        </div>
    </div>
@endif

resources/views/layouts/inc/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                {{ date('Y') }} © {{ env('APP_NAME') }}.
            </div>
            <div class="col-sm-6">
                <div class="text-sm-end d-none d-sm-block">
                    @lang('Development by Eslam Mohsen Handosua')
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/layouts/inc/head.blade.php
<meta charset="utf-8" />
<title>{{ env('APP_NAME') }}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
<meta content="Themesbrand" name="author" />
<meta name="csrf-token" content="{{ csrf_token() }}"/>
<base href="{{ url('/') }}">
<link rel="shortcut icon" href="assets/images/favicon.ico">
<link href="assets/css/bootstrap.min.css" id="bootstrap-style" rel="stylesheet" type="text/css" />
<link href="assets/css/icons.min.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="assets/libs/toastr/build/toastr.min.css">
<link href="assets/libs/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet" type="text/css" />
<link href="assets/css/app.min.css" id="app-style" rel="stylesheet" type="text/css" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Changa:wght@700&display=swap" rel="stylesheet">

@stack('styles')
<style>
    body{
        font-family: 'Changa', sans-serif;
    }
    .saloka_overlay{
        background: #222736;
        width: 100%;
        height: 100vh;
        position: absolute;
        top: 0px;
        z-index: 99999;
        text-align: center;
    }
    .make_pad{
        font-weight: bolder;
        padding: 7px;
    }
    .help-block{
        color: red;
    }
    @media  only screen and (max-width: 992px) {
        .hideMe {
            display: none;
        }
        .page-title-right {
            display: none;
        }
    }
</style>

resources/views/layouts/inc/header.blade.php
<header id="page-topbar">
    <div class="navbar-header">
        <div class="d-flex">
            <!-- LOGO -->
            <div class="navbar-brand-box hideMe">
                <p style=" color: white; margin-top: 22px; font-weight: bold; font-size: 20px; ">
                    {{ env('APP_NAME') }}
                </p>
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-16 header-item waves-effect" id="vertical-menu-btn">
                <i class="fa fa-fw fa-bars"></i>
            </button>
        </div>

        <div class="d-flex">
            <div class="dropdown d-none d-lg-inline-block ms-1">
                <button type="button" class="btn header-item noti-icon waves-effect" data-toggle="fullscreen">
                    <i class="bx bx-fullscreen"></i>
                </button>
            </div>


            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="rounded-circle header-profile-user" src="{{ display_image_by_model(\Auth::user(),'avatar') }}" alt="Header Avatar">
                    <span class="d-none d-xl-inline-block ms-1" key="t-{{ \Auth::user()->name }}">{{ \Auth::user()->name }}</span>
                    <i class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-end">
                    <!-- item-->
                    <a class="dropdown-item" href="{{ route('profile.index') }}"><i class="bx bx-user font-size-16 align-middle me-1"></i> <span key="t-profile">@lang('Profile')</span></a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item text-danger" href="{{ route('logout') }}"><i class="bx bx-power-off font-size-16 align-middle me-1 text-danger"></i> <span key="t-logout">@lang('Logout')</span></a>
                </div>
            </div>

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item noti-icon right-bar-toggle waves-effect">
                    <i class="bx bx-cog bx-spin"></i>
                </button>
            </div>

        </div>
    </div>
</header>

resources/views/layouts/inc/menu.blade.php
<!-- ========== Left Sidebar Start ========== -->
<div class="vertical-menu">

    <div data-simplebar class="h-100">

        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled" id="side-menu">
                <li class="menu-title" key="t-menu"><span style="font-size: 15px">@lang('Menu')</span></li>
                <li>
                    <a href="{{ route('home') }}" class="waves-effect">
                        <i class="bx bx-home-circle"></i>
                        <span key="t-dashboards">
                            @lang('Dashboard')
                        </span>
                    </a>
                </li>
                @if (\Auth::user()->user_type == "admin")
                    <li>
                        <a href="{{ route('users.index') }}" class="waves-effect">
                            <i class="bx bx-home-circle"></i>
                            <span key="t-dashboards">
                                @lang('Users')
                            </span>
                        </a>
                    </li>
                @endif
                <li>
                    <a href="{{ route('ads.index') }}" class="waves-effect">
                        <i class="bx bx-home-circle"></i>
                        <span key="t-dashboards">
                            @lang('Ads')
                        </span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- Sidebar -->
    </div>
</div>
<!-- Left Sidebar End -->

resources/views/layouts/inc/paginator.blade.php
@if ($paginator->hasPages())

    <div class="row">
        <div class="col-lg-12">
            <ul class="pagination pagination-rounded justify-content-center mt-3 mb-4 pb-1">

                @if ($paginator->onFirstPage())
                    <li class="page-item disabled" aria-disabled="true" aria-label="@lang('pagination.previous')">
                        <span class="page-link" aria-hidden="true">&lsaquo;</span>
                    </li>
                @else
                    <li class="page-item">
                        <a class="page-link" href="{{ $paginator->previousPageUrl() }}" rel="prev" aria-label="@lang('pagination.previous')">&lsaquo;</a>
                    </li>
                @endif


                @foreach ($elements as $element)
                    {{-- "Three Dots" Separator --}}
                    @if (is_string($element))
                        <li class="page-item disabled" aria-disabled="true"><span class="page-link">{{ $element }}</span></li>
                    @endif

                    {{-- Array Of Links --}}
                    @if (is_array($element))
                        @foreach ($element as $page => $url)
                            @if ($page == $paginator->currentPage())
                                <li class="page-item active" aria-current="page"><span class="page-link">{{ $page }}</span></li>
                            @else
                                <li class="page-item"><a class="page-link" href="{{ $url }}">{{ $page }}</a></li>
                            @endif
                        @endforeach
                    @endif
                @endforeach


                @if ($paginator->hasMorePages())
                    <li class="page-item">
                        <a class="page-link" href="{{ $paginator->nextPageUrl() }}" rel="next" aria-label="@lang('pagination.next')">&rsaquo;</a>
                    </li>
                @else
                    <li class="page-item disabled" aria-disabled="true" aria-label="@lang('pagination.next')">
                        <span class="page-link" aria-hidden="true">&rsaquo;</span>
                    </li>
                @endif


            </ul>
        </div>
    </div>

@endif

resources/views/layouts/inc/right-bar.blade.php
<!-- Right Sidebar -->
<div class="right-bar">
    <div data-simplebar class="h-100">
        <div class="rightbar-title d-flex align-items-center px-3 py-4">
            <h5 class="m-0 me-2">@lang('Settings')</h5>
            <a href="javascript:void(0);" class="right-bar-toggle ms-auto">
                <i class="mdi mdi-close noti-icon"></i>
            </a>
        </div>
        <hr class="mt-0" />
        <h6 class="text-center mb-0">
            @lang('Choose Layouts')
        </h6>

        <div class="p-4">
            <div class="mb-2">
                <img src="{{ url('/assets/images/layouts/layout-1.jpg') }}" class="img-thumbnail" alt="layout images">
            </div>

            <div class="form-check form-switch mb-3">
                <input class="form-check-input theme-choice" type="radio" name="ddr" id="light-mode-switch" checked>
                <label class="form-check-label" for="light-mode-switch">
                    @lang('Light Mode')
                </label>
            </div>

            <div class="mb-2">
                <img src="{{ url('/assets/images/layouts/layout-2.jpg') }}" class="img-thumbnail" alt="layout images">
            </div>
            <div class="form-check form-switch mb-3">
                <input class="form-check-input theme-choice" type="radio" name="ddr" id="dark-mode-switch">
                <label class="form-check-label" for="dark-mode-switch">
                    @lang('Dark Mode')
                </label>
            </div>

        </div>

    </div> <!-- end slimscroll-menu-->
</div>
<!-- /Right-bar -->

resources/views/layouts/inc/scripts.blade.php
<div class="rightbar-overlay"></div>
<script src="assets/libs/jquery/jquery.min.js"></script>
<script src="assets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="assets/libs/metismenu/metisMenu.min.js"></script>
<script src="assets/libs/simplebar/simplebar.min.js"></script>
<script src="assets/libs/node-waves/waves.min.js"></script>

<script src="assets/libs/toastr/build/toastr.min.js"></script>
<script src="assets/js/pages/toastr.init.js"></script>

<script src="assets/js/app.js"></script>

<script>
    toastr.options = {
        "closeButton": false,
        "debug": false,
        "newestOnTop": false,
        "progressBar": false,
        "positionClass": "toast-bottom-right",
        "preventDuplicates": false,
        "onclick": null,
        "showDuration": 300,
        "hideDuration": 1000,
        "timeOut": 5000,
        "extendedTimeOut": 1000,
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    }
</script>
@if (Session::get('success'))
    <script>
        toastr["success"]("{{ Session::get('success') }}")
    </script>
@endif
@if (Session::get('danger'))
    <script>
        toastr["warning"]("{{ Session::get('danger') }}")
    </script>
@endif




<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">
                    @lang('Delete This row')
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>
                    @lang('Are you sure, You want to delete this row')
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light" data-bs-dismiss="modal">@lang('No')</button>
                <button type="button" class="btn btn-primary actionMyDelete">@lang('Yes')</button>
            </div>
        </div>
    </div>
</div>

<script>
    var row_deleted = 0;
    $('.row_deleted').click(function(e){
        e.preventDefault();
        row_deleted = $(this).data('id'); 
    });
    $('.actionMyDelete').click(function(e){
        e.preventDefault();
        $('#form_'+row_deleted).submit();
    });

    $('.makeAction').click(function(e){
        if (!window.confirm("@lang('are you sure ?')")) {
            e.preventDefault();
        }
    });
</script>

@includeIf('layouts.inc.push')

@stack('scripts')