routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdsController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    // Logout
    Route::get('/logout', [HomeController::class,'logout'])->name('logout');
    // Profile
    Route::get('/profile', [ProfileController::class,'index'])->name('profile.index');
    Route::post('/profile', [ProfileController::class,'store'])->name('profile.store');
    // Home
    Route::get('/', [HomeController::class,'index'])->name('home');

    Route::resource('users', UserController::class);
    Route::resource('ads', AdsController::class);
});

app/Models/Ads.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Ads extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'title',
        'description',
        'image',
    ];

    public function user() {
        return $this->hasOne(User::class,'id','user_id');
    }
}

app/Http/Controllers/API/AdsController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
// Request
use Illuminate\Http\Request;
use App\Http\Requests\API\Ads\CreateOrUpdateRequest;
// Resources
use App\Http\Resources\Api\Ads\AdsResource;
// Models
use App\Models\Ads;
// API
use App\Support\API;

class AdsController extends Controller
{
    public function index() {
        $lists = Ads::orderBy('id', 'desc')->paginate();
        return (new API)->isOk(__("Ads lists"))->setData(AdsResource::collection($lists))->addAttribute('paginate',api_model_set_pagination($lists))->build();
    }

    public function myAds() {
        $lists = \Auth::user()->ads()->orderBy('id', 'desc')->paginate();
        return (new API)->isOk(__("My ads lists"))->setData(AdsResource::collection($lists))->addAttribute('paginate',api_model_set_pagination($lists))->build();
    }

    public function show(Ads $ad) {
        return (new API)->isOk(__("ads information"))->setData(new AdsResource($ad))->build();
    }

    public function store(CreateOrUpdateRequest $request, Ads $ad) {
        $request = $request->all();
        $request = $this->uploadFiles($request , $request);
        $ad = \Auth::user()->ads()->create($request);
        return (new API)->isOk(__("ads information"))->setData(new AdsResource($ad))->build();
    }

    public function update(CreateOrUpdateRequest $request,Ads $ad) {
        if(\Auth::user()->id != $ad->user_id) {
            return (new API)->isError(__("You can't updated this ads."))->build();
        }
        $request = $request->all();
        $request = $this->uploadFiles($request , $request);
        $ad->update($request);
        return (new API)->isOk(__("this ads has been updated"))->setData(new AdsResource($ad))->build();
    }

    public function destroy(Ads $ad) {
        if(\Auth::user()->id != $ad->user_id) {
            return (new API)->isError(__("You can't delete this ads."))->build();
        }
        $ad->delete();
        return (new API)->isOk(__("this ads has been delete"))->build();
    }


    public function uploadFiles($request)
    {
        if(request()->has('image') && !is_null(request('image'))) {
            $request['image'] = imageUpload($request['image'],'adv');
        } else {
            if (isset($request['image'])){
                unset($request['image']);
            }
        }

        return $request;
    }
}

app/Http/Controllers/AdsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Http\Requests\Ads\CreateOrUpdateRequest;
use App\Models\Ads;
use Illuminate\Http\Request;

class AdsController extends Controller
{
    public function index() {

        $breadcrumb = [
            'title' =>  __("Ads lists"),
            'items' =>  [
                [
                    'title' =>  __("Ads Lists"),
                    'url'   =>  '#!',
                ]
            ],
        ];
        $lists = Ads::orderBy('id', 'desc')->paginate();
        return view('pages.ads.index',[
            'breadcrumb'=>$breadcrumb,
            'lists'=>$lists,
        ]);
    }

    public function create() {
        $breadcrumb = [
            'title' =>  __("Create new ads"),
            'items' =>  [
                [
                    'title' =>  __("Ads Lists"),
                    'url'   => route('ads.index'),
                ],
                [
                    'title' =>  __("Create new ads"),
                    'url'   =>  '#!',
                ],
            ],
        ];

        return view('pages.ads.create',[
            'breadcrumb'=>$breadcrumb,
        ]);
    }

    public function store(CreateOrUpdateRequest $request) {
        $request = $request->all();
        $request = $this->uploadFiles($request , $request);
        \Auth::user()->ads()->create($request);
        return redirect()->route('ads.index')->with('success', __("This ads has been created."));
    }

    public function show(Ads $ad) {
        $breadcrumb = [
            'title' =>  __("Show ads"),
            'items' =>  [
                [
                    'title' =>  __("Ads Lists"),
                    'url'   => route('ads.index'),
                ],
                [
                    'title' =>  __("Show ads"),
                    'url'   =>  '#!',
                ],
            ],
        ];

        return view('pages.ads.show',[
            'breadcrumb'=>$breadcrumb,
            'ad'=>$ad,
        ]);
    }

    public function edit(Ads $ad) {
        if(\Auth::user()->id != $ad->user_id) {
            return redirect()->route('ads.index')->with('success', __("You can't edit this ads."));
        }
        $breadcrumb = [
            'title' =>  __("Edit ads"),
            'items' =>  [
                [
                    'title' =>  __("Ads Lists"),
                    'url'   => route('ads.index'),
                ],
                [
                    'title' =>  __("Edit ads"),
                    'url'   =>  '#!',
                ],
            ],
        ];

        return view('pages.ads.edit',[
            'breadcrumb'=>$breadcrumb,
            'ad'=>$ad,
        ]);
    }

    public function update(CreateOrUpdateRequest $request, Ads $ad) {
        if(\Auth::user()->id != $ad->user_id) {
            return redirect()->route('ads.index')->with('success', __("You can't update this ads."));
        }
        $request = $request->all();
        $request = $this->uploadFiles($request , $request);
        $ad->update($request);
        return redirect()->route('ads.index')->with('success', __("This ads has been updated."));
    }

    public function destroy(Request $request,Ads $ad) {
        if(\Auth::user()->id != $ad->user_id) {
            return redirect()->route('ads.index')->with('success', __("You can't delete this ads."));
        }
        $ad->delete();
        return redirect()->route('ads.index')->with('success', __("This ads has been deleted."));
    }

    public function uploadFiles($request)
    {
        if(request()->has('image') && !is_null(request('image'))) {
            $request['image'] = imageUpload($request['image'],'adv');
        } else {
            if (isset($request['image'])){
                unset($request['image']);
            }
        }

        return $request;
    }
}

resources/views/pages/ads/create.blade.php
@extends('layouts.master')
@section('PageTitle',$breadcrumb['title'])
@section('PageContent')
@includeIf('layouts.inc.breadcrumb')



<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <form action="{{ route('ads.store') }}" method="post" enctype="multipart/form-data">
                    <h5 class="font-size-14">
                        <i class="mdi mdi-arrow-right text-primary"></i>
                        @lang('General information')
                    </h5>

                    <div class="mb-3 row">
                        <label for="user_avatar" class="col-form-label col-lg-2">@lang('Title')</label>
                        <div class="col-lg-10">
                            <input class="form-control" placeholder="@lang('Title')" value="{{ old('title') }}" type="text" name="title" id="user_avatar">
                            @error('name')
                                <span style="color:red;">
                                    {{ $errors->first('name') }}
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="mb-3 row">
                        <label for="user_avatar" class="col-form-label col-lg-2">@lang('Description')</label>
                        <div class="col-lg-10">
                            <textarea class="form-control" placeholder="@lang('Description')" name="description" cols="30" rows="10">{{ old('description') }}</textarea>
                            @error('description')
                                <span style="color:red;">
                                    {{ $errors->first('description') }}
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="mb-3 row">
                        <label for="user_avatar" class="col-form-label col-lg-2">@lang('Image')</label>
                        <div class="col-lg-10">
                            <input class="form-control" type="file" name="image" id="user_avatar">
                            @error('image')
                                <span style="color:red;">
                                    {{ $errors->first('image') }}
                                </span>
                            @enderror
                        </div>
                    </div>


                    <div class="row" style=" margin-top: 20px; ">
                        <div style="text-align: right">
                            @csrf
                            <button type="submit" class="btn btn-primary w-md">@lang('Submit')</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div> <!-- end col -->
</div>


@endsection

resources/views/pages/ads/edit.blade.php
@extends('layouts.master')
@section('PageTitle',$breadcrumb['title'])
@section('PageContent')
@includeIf('layouts.inc.breadcrumb')



<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <form action="{{ route('ads.update',$ad->id) }}" method="post" enctype="multipart/form-data">
                    <h5 class="font-size-14">
                        <i class="mdi mdi-arrow-right text-primary"></i>
                        @lang('General information')
                    </h5>

                    <div class="mb-3 row">
                        <label for="user_avatar" class="col-form-label col-lg-2">@lang('Title')</label>
                        <div class="col-lg-10">
                            <input class="form-control" placeholder="@lang('Title')" value="{{ old('title',$ad->title) }}" type="text" name="title" id="user_avatar">
                            @error('name')
                                <span style="color:red;">
                                    {{ $errors->first('name') }}
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="mb-3 row">
                        <label for="user_avatar" class="col-form-label col-lg-2">@lang('Description')</label>
                        <div class="col-lg-10">
                            <textarea class="form-control" placeholder="@lang('Description')" name="description" cols="30" rows="10">{{ old('description',$ad->description) }}</textarea>
                            @error('description')
                                <span style="color:red;">
                                    {{ $errors->first('description') }}
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="mb-3 row">
                        <label for="user_avatar" class="col-form-label col-lg-2">@lang('Image')</label>
                        <div class="col-lg-9">
                            <input class="form-control" type="file" name="image" id="user_avatar">
                            @error('image')
                                <span style="color:red;">
                                    {{ $errors->first('image') }}
                                </span>
                            @enderror
                        </div>
                        @if(isset($ad))
                            <div class="col-lg-1">
                                <a href="{{ display_image_by_model($ad,'image') }}" target="_blank">
                                    <img src="{{ display_image_by_model($ad,'image') }}" alt="" class="rounded-circle header-profile-user">
                                </a>
                            </div>
                        @endif
                    </div>

                    <div class="row" style=" margin-top: 20px; ">
                        <div style="text-align: right">
                            @csrf
                            @method('PUT')
                            <button type="submit" class="btn btn-primary w-md">@lang('Submit')</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div> <!-- end col -->
</div>


@endsection

resources/views/pages/ads/index.blade.php
@extends('layouts.master')
@section('PageTitle',$breadcrumb['title'])
@section('PageContent')
@includeIf('layouts.inc.breadcrumb')

<div style=" margin-bottom: 14px; position: relative; text-align: right; ">
    <a type="button" class="btn btn-primary my-action"  href="{{route('ads.create')}}">@lang('Create new ads')</a>
</div>


@if ($lists->count() > 0)

    <div class="row">
        <div class="col-lg-12">
            <div class="">
                <div class="table-responsive">
                    <table class="table project-list-table table-nowrap align-middle table-borderless">
                        <thead>
                            <tr>
                                <th scope="col">@lang('User')</th>
                                <th scope="col">@lang('Title')</th>
                                <th scope="col">@lang('Created At')</th>
                                <th scope="col">@lang('Action')</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($lists as $list)
                                <tr>
                                    <td>
                                        {{ $list->user->name ?? '' }}
                                    </td>
                                    <td>
                                        {{ $list->title ?? '' }}
                                    </td>
                                    <td>
                                        {{ $list->created_at}}
                                    </td>
                                    <td style="display: inline-flex;">
                                        <a style="margin-right: 5px;"
                                            class="btn btn-outline-secondary btn-sm edit"
                                            href="{{ route('ads.show',$list->id) }}">
                                            <i class="fas fa-eye"></i>
                                        </a>
                                        @if (\Auth::user()->id == $list->user_id)
                                            <a style="margin-right: 5px;"
                                                class="btn btn-outline-secondary btn-sm edit"
                                                href="{{ route('ads.edit',$list->id) }}">
                                                <i class="fas fa-pencil-alt"></i>
                                            </a>
                                            {!! action_table_delete(route('ads.destroy',$list->id),$list->id) !!}
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    {{ $lists->links('layouts.inc.paginator') }}
@else

    <div class="row">
        <div class="col-lg-12">
            <div class="text-center">
                <div class="row justify-content-center mt-5">
                    <div class="col-sm-4">
                        <div class="maintenance-img">
                            <img src="{{ url('assets/images/verification-img.png') }}" alt="" class="img-fluid mx-auto d-block">
                        </div>
                    </div>
                </div>
                <h4 class="mt-5">@lang("Let's get started")</h4>
                <p class="text-muted">@lang("Oops, We don't have users").</p>
            </div>
        </div>
    </div>


@endif

@endsection

resources/views/pages/ads/show.blade.php
@extends('layouts.master')
@section('PageTitle',$breadcrumb['title'])
@section('PageContent')
@includeIf('layouts.inc.breadcrumb')


<div class="row">
    <div class="col-lg-8">
        <div class="card">
            <div class="card-body" style=" position: relative; ">
                <h5 class="font-size-15">@lang('Ads Details') :</h5>
                <p class="text-muted">
                    {!! $ad->description !!}
                </p>
            </div>
        </div>
    </div>

    <div class="col-lg-4">

        <div class="">
            <div class="table-responsive">
                <table class="table project-list-table table-nowrap align-middle table-borderless">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">##</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                @lang('Title')
                            </td>
                            <td>
                                {{ $ad->title }}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @lang('Name')
                            </td>
                            <td>
                                {{ $ad->user->name }} ( {{ ucfirst($ad->user->user_type ?? '') }} )
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @lang('Email')
                            </td>
                            <td>
                                <a href="mailto:{{ $ad->user->email }}">{{ $ad->user->email }}</a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @lang('Created At')
                            </td>
                            <td>
                                {{ $ad->created_at }}
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <h4 class="card-title mb-4">@lang('Ads Image')</h4>
                <div class="table-responsive">
                    <center>
                        <img src="{{ display_image_by_model($ad,'image') }}" style=" width: 100%; height: 100px; ">
                    </center>
                </div>
            </div>
        </div>


    </div>
</div>


@endsection