routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdsController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    // Logout
    Route::get('/logout', [HomeController::class,'logout'])->name('logout');
    // Profile
    Route::get('/profile', [ProfileController::class,'index'])->name('profile.index');
    Route::post('/profile', [ProfileController::class,'store'])->name('profile.store');
    // Home
    Route::get('/', [HomeController::class,'index'])->name('home');

    Route::resource('users', UserController::class);
    Route::resource('ads', AdsController::class);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'api_token',
        'avatar',
        'user_type',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function ads() {
        return $this->hasMany(Ads::class,'user_id','id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Http\Requests\User\CreateUserRequest;
use App\Http\Requests\User\UpdateUserRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class UserController extends Controller
{
    public function index() {

        $breadcrumb = [
            'title' =>  __("Users lists"),
            'items' =>  [
                [
                    'title' =>  __("Users Lists"),
                    'url'   =>  '#!',
                ]
            ],
        ];

        return view('pages.users.index',[
            'breadcrumb'=>$breadcrumb,
            'lists'=>User::orderBy('created_at', 'desc')->paginate(),
        ]);
    }

    public function create() {
        $breadcrumb = [
            'title' =>  __("Create New User"),
            'items' =>  [
                [
                    'title' =>  __("Users Lists"),
                    'url'   => route('users.index'),
                ],
                [
                    'title' =>  __("Create New User"),
                    'url'   =>  '#!',
                ],
            ],
        ];

        return view('pages.users.create',[
            'breadcrumb'=>$breadcrumb,
        ]);
    }

    public function store(CreateUserRequest $request) {
        $data = $request->all();
        $data['password'] = Hash::make($request['password']);
        $data['email_verified_at'] = Carbon::now();
        $data = $this->uploadFiles($request , $data);
        $user = User::create($data);
        return redirect()->route('users.index')->with('success', __("This user has been created."));
    }

    public function edit(User $user) {
        $breadcrumb = [
            'title' =>  __("Edit user"),
            'items' =>  [
                [
                    'title' =>  __("Users Lists"),
                    'url'   => route('users.index'),
                ],
                [
                    'title' =>  __("Edit user"),
                    'url'   =>  '#!',
                ],
            ],
        ];

        return view('pages.users.edit',[
            'breadcrumb'=>$breadcrumb,
            'user'=>$user,
        ]);
    }

    public function update(UpdateUserRequest $request, User $user) {
        $data = $request->all();
        if(request()->has('password') && !is_null(request('password'))) {
            $data['password'] = Hash::make($request['password']);
        } else {
            unset($data['password']);
        }
        $data = $this->uploadFiles($request , $data);
        $user->update($data);
        return redirect()->route('users.index')->with('success', __("This user has been updated."));
    }

    public function destroy(Request $request,User $user) {
        $user->delete();
        return redirect()->route('users.index')->with('success', __("This user has been deleted."));
    }

    public function uploadFiles($request , $data)
    {
        if(request()->has('avatar') && !is_null(request('avatar'))) {
            $data['avatar'] = imageUpload($request['avatar'],'users');
        } else {
            if (isset($request['avatar'])){
                unset($request['avatar']);
            }
        }

        return $data;
    }
}

resources/views/pages/users/create.blade.php
@extends('layouts.master')
@section('PageTitle',$breadcrumb['title'])
@section('PageContent')
@includeIf('layouts.inc.breadcrumb')



<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <form action="{{ route('users.store') }}" method="post" enctype="multipart/form-data">
                    <h5 class="font-size-14">
                        <i class="mdi mdi-arrow-right text-primary"></i>
                        @lang('General information')
                    </h5>

                    <div class="mb-3 row">
                        <label for="user_avatar" class="col-form-label col-lg-2">@lang('Name')</label>
                        <div class="col-lg-10">
                            <input class="form-control" value="{{ old('name') }}" type="text" name="name" id="user_avatar">
                            @error('name')
                                <span style="color:red;">
                                    {{ $errors->first('name') }}
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="mb-3 row">
                        <label for="user_avatar" class="col-form-label col-lg-2">@lang('Email')</label>
                        <div class="col-lg-10">
                            <input class="form-control" value="{{ old('email') }}" type="email" name="email">
                            @error('email')
                            <span style="color:red;">
                                    {{ $errors->first('email') }}
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="mb-3 row">
                        <label for="user_avatar" class="col-form-label col-lg-2">@lang('Password')</label>
                        <div class="col-lg-10">
                            <input class="form-control" value="{{ old('password') }}" type="password" name="password">
                            @error('password')
                            <span style="color:red;">
                                    {{ $errors->first('password') }}
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="mb-3 row">
                        <label for="user_avatar" class="col-form-label col-lg-2">@lang('Image')</label>
                        <div class="col-lg-10">
                            <input class="form-control" type="file" name="avatar" id="user_avatar">
                            @error('avatar')
                                <span style="color:red;">
                                    {{ $errors->first('avatar') }}
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="row col-12 mb-3">

                        <label for="head" class="col-form-label col-lg-2">
                            @lang('User Type')
                        </label>
                        <div class="col-lg-10">
                            <select name="user_type" class="form-control">
                                <option value="admin">admin</option>
                                <option value="client">client</option>
                            </select>
                            @error('user_type')
                                <span style="color:red;">
                                    {{ $errors->first('user_type') }}
                                </span>
                            @enderror
                        </div>
                    </div>



                    <div class="row" style=" margin-top: 20px; ">
                        <div style="text-align: right">
                            @csrf
                            <button type="submit" class="btn btn-primary w-md">@lang('Submit')</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div> <!-- end col -->
</div>


@endsection

resources/views/pages/users/edit.blade.php
@extends('layouts.master')
@section('PageTitle',$breadcrumb['title'])
@section('PageContent')
@includeIf('layouts.inc.breadcrumb')



<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <form action="{{ route('users.update',$user->id) }}" method="post" enctype="multipart/form-data">
                    <h5 class="font-size-14">
                        <i class="mdi mdi-arrow-right text-primary"></i>
                        @lang('General information')
                    </h5>

                    <div class="mb-3 row">
                        <label for="user_avatar" class="col-form-label col-lg-2">@lang('Name')</label>
                        <div class="col-lg-10">
                            <input class="form-control" value="{{ old('name',$user->name) }}" type="text" name="name" id="user_avatar">
                            @error('name')
                                <span style="color:red;">
                                    {{ $errors->first('name') }}
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="mb-3 row">
                        <label for="user_avatar" class="col-form-label col-lg-2">@lang('Email')</label>
                        <div class="col-lg-10">
                            <input class="form-control" value="{{ old('email',$user->email) }}" type="email" name="email" required>
                            @error('email')
                            <span style="color:red;">
                                    {{ $errors->first('email') }}
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="mb-3 row">
                        <label for="user_avatar" class="col-form-label col-lg-2">@lang('Password')</label>
                        <div class="col-lg-10">
                            <input class="form-control" type="password" name="password">
                            @error('password')
                            <span style="color:red;">
                                    {{ $errors->first('password') }}
                                </span>
                            @enderror
                        </div>
                    </div>


                    <div class="mb-3 row">
                        <label for="user_avatar" class="col-form-label col-lg-2">@lang('Image')</label>
                        <div class="col-lg-9">
                            <input class="form-control" type="file" name="avatar" id="user_avatar">
                            @error('avatar')
                                <span style="color:red;">
                                    {{ $errors->first('avatar') }}
                                </span>
                            @enderror
                        </div>
                        @if(isset($user))
                            <div class="col-lg-1">
                                <a href="{{ display_image_by_model($user,'avatar') }}" target="_blank">
                                    <img src="{{ display_image_by_model($user,'avatar') }}" alt="" class="rounded-circle header-profile-user">
                                </a>
                            </div>
                        @endif
                    </div>

                    <div class="row col-12 mb-3">

                        <label for="head" class="col-form-label col-lg-2">
                            @lang('User Type')
                        </label>
                        <div class="col-lg-10">
                            <select name="user_type" class="form-control">
                                <option @if($user->user_type == "admin") selected @endif value="admin">admin</option>
                                <option @if($user->user_type == "client") selected @endif value="client">client</option>
                            </select>
                            @error('user_type')
                                <span style="color:red;">
                                    {{ $errors->first('user_type') }}
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="row" style=" margin-top: 20px; ">
                        <div style="text-align: right">
                            @csrf
                            @method('PUT')
                            <button type="submit" class="btn btn-primary w-md">@lang('Submit')</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div> <!-- end col -->
</div>


@endsection

resources/views/pages/users/index.blade.php
@extends('layouts.master')
@section('PageTitle',$breadcrumb['title'])
@section('PageContent')
@includeIf('layouts.inc.breadcrumb')

<div style=" margin-bottom: 14px; position: relative; text-align: right; ">
    <a type="button" class="btn btn-primary my-action"  href="{{route('users.create')}}">@lang('Create new user')</a>
</div>


@if ($lists->count() > 0)

    <div class="row">
        <div class="col-lg-12">
            <div class="">
                <div class="table-responsive">
                    <table class="table project-list-table table-nowrap align-middle table-borderless">
                        <thead>
                            <tr>
                                <th scope="col">@lang('Name')</th>
                                <th scope="col">@lang('Email')</th>
                                <th scope="col">@lang('Created At')</th>
                                <th scope="col">@lang('Roles')</th>
                                <th scope="col">@lang('Action')</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($lists as $list)
                                <tr>
                                    <td>
                                        {{ $list->name ?? '' }}
                                    </td>
                                    <td>
                                        {{ $list->email ?? '' }}
                                    </td>
                                    <td>
                                        {{ $list->created_at}}
                                    </td>
                                    <td>
                                        {{ ucfirst($list->user_type) }}
                                    </td>
                                    <td style="display: inline-flex;">
                                        <a style="margin-right: 5px;"
                                            class="btn btn-outline-secondary btn-sm edit"
                                            href="{{ route('users.edit',$list->id) }}">
                                            <i class="fas fa-pencil-alt"></i>
                                        </a>
                                        {!! action_table_delete(route('users.destroy',$list->id),$list->id) !!}
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    {{ $lists->links('layouts.inc.paginator') }}
@else

    <div class="row">
        <div class="col-lg-12">
            <div class="text-center">
                <div class="row justify-content-center mt-5">
                    <div class="col-sm-4">
                        <div class="maintenance-img">
                            <img src="{{ url('assets/images/verification-img.png') }}" alt="" class="img-fluid mx-auto d-block">
                        </div>
                    </div>
                </div>
                <h4 class="mt-5">@lang("Let's get started")</h4>
                <p class="text-muted">@lang("Oops, We don't have users").</p>
            </div>
        </div>
    </div>


@endif

@endsection